// Code generated by Slice Machine. DO NOT EDIT.

import Cards from './Cards';
import Cards2 from './Cards2';
import Emergencies from './Emergencies';
import Footer from './Footer';
import Header from './Header';
import HeaderOne from './HeaderOne';
import Heroslice from './Heroslice';
import Images from './Images';
import Map from './Map';
import Maps from './Maps';
import Smilegallery from './Smilegallery';

export {
	Cards,
	Cards2,
	Emergencies,
	Footer,
	Header,
	HeaderOne,
	Heroslice,
	Images,
	Map,
	Maps,
	Smilegallery,
};

export const components = {
	cards: Cards,
	cards2: Cards2,
	emergencies: Emergencies,
	footer: Footer,
	header: Header,
	header_one: HeaderOne,
	heroslice: Heroslice,
	images: Images,
	map: Map,
	mpas: Maps,
	smilegallery: Smilegallery,
};
