import { Html, Head, Main, NextScript } from 'next/document'

export default function Document() {
  return (
    <Html lang="en">
      <Head />
      <title>My Gentle Dentist</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="png" href="/Logo.png" />
        <body data-scroll-time="2.0">
          <Main />
          <NextScript />
        </body>
    </Html>
  )
}
